name: Check formatting

on: [push]

jobs:

  code_style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install bibtool moreutils

      - name: Check formatting
        run: ./format --file literature.bib --output output.bib --check
